name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:dd-MM-yyyy)$(Rev:.r)

trigger: none
  
variables:
  location: westeurope

pool:
  vmImage: windows-latest

stages:
  - stage: DEV
    variables:
      environment: DEV
      resourceGroupName: $(environment)_$(rgName)
      region: $(location)
    jobs:
      - job:
        displayName: Déploiement $(environment) ($(location))
        steps:
        - template: TemplateRG.yml
          parameters:
            location: $(region)
            rgName: $(resourceGroupName)
            environnement: $(environment)

        - template: TemplateAppService.yml
          parameters:
            rgName: $(resourceGroupName)
            location: $(region)

  - stage: PROD_EU
    variables:
      environment: PROD_EU
      resourceGroupName: $(environment)_$(rgName)
      region: $(location)
    dependsOn: [DEV]
    jobs:
    - template: deployInfra.yml
      parameters:
        location: $(region)
        rgName: $(resourceGroupName)
        environnement: $(environment)

  - stage: PROD_US
    variables:
      environment: PROD_US
      resourceGroupName: $(environment)_$(rgName)
      region: westus
    dependsOn: [DEV]
    jobs:
    - template: deployInfra.yml
      parameters:
        location: $(region)
        rgName: $(resourceGroupName)
        environnement: $(environment)
